# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058049488e407fb1e6cde1565d07f4faffaf798a8a31e2c4dde6de89f21d552580038a404955761f2c25965de9093349cc4cba207fdca33c7bab9b0a7a525d96

test:
  secret_key_base: 5f3e503fec6fa76157369473253d66ecd195f167b83f8d4bbbb1d2af2408a394d6ccf567a0a2ae8c7ecaabc3fa6f51f6cf48abe226436f8af98f9f1e92c2bb1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
